apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    run: rabbitmq-service
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 31801
    protocol: TCP
    name: tcp
  - port: 15672
    nodePort: 31802
    targetPort: 15672
    protocol: TCP
    name: http
  selector:
    app: rabbitmq