apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  labels:
    app: cassandra
spec:
  type: NodePort
  ports:
  - port: 9042
    targetPort: 9042
    nodePort: 31803
    protocol: TCP
    name: tcp
  selector:
    app: cassandra