apiVersion: v1
kind: Service
metadata:
  name: k8s-service-service
spec:
  type: NodePort
  ports:
  - port: 9988
    targetPort: 9988
    nodePort: 31804
    protocol: TCP
    name: tcp
  selector:
    app: k8s-service
